version: '2'
services:
  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  bg_match_app:
    build: .
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 'pass'
      MYSQL_HOST: mysql
      DATABASE_URL: mysql2://root:pass@mysql:3306
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/bg_match_app
      - bundle:/bundle
    links:
      - mysql
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mysql
      
volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local