version: 2
jobs:
  build:
    working_directory: ~/bg_match_app
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
        - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: テストデータベース作成とマイグレーション
          command: docker-compose exec bg_match_app bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
          name: RSpec実行
          command: docker-compose exec bg_match_app bundle exec bin/rspec
      - run:
          name: Rubocop実行
          command: docker-compose exec bg_match_app bundle exec rubocop
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down