default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
development:
  <<: *default
  database: bg_match_app_development

test:
  <<: *default
  database: bg_match_app_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  url: <%= ENV['CLEARDB_DATABASE_URL']&.sub('mysql://', 'mysql2://') %>
